// Authoritative settings file. Every configured value the binaries use is
// declared once there and validated here, so no target carries a literal
// default for a configured value.
const SETTINGS_FILE: &str = "kwin-mcp.toml";

// Accepted ranges, in milliseconds, for the viewer key-state timings.
const NUMLOCK_CONFIRM_TIMEOUT_MS: std::ops::RangeInclusive<u64> = 50..=60_000;
const DISPATCH_POLL_INTERVAL_MS: std::ops::RangeInclusive<u64> = 1..=5_000;

#[derive(serde::Deserialize)]
#[serde(deny_unknown_fields)]
struct Settings {
    viewer: ViewerSettings,
}

#[derive(serde::Deserialize)]
#[serde(deny_unknown_fields)]
struct ViewerSettings {
    keystate: KeyStateSettings,
}

#[derive(serde::Deserialize)]
#[serde(deny_unknown_fields)]
struct KeyStateSettings {
    numlock_confirm_timeout_ms: u64,
    dispatch_poll_interval_ms: u64,
}

fn check_range(name: &str, value: u64, range: &std::ops::RangeInclusive<u64>) {
    if !range.contains(&value) {
        panic!(
            "{SETTINGS_FILE}: [viewer.keystate] {name} = {value} is outside {}..={} ms",
            range.start(),
            range.end()
        );
    }
}

// Turn the settings file into the constants the viewer compiles against.
// Failing here is intentional: an unreadable, malformed, or out-of-range
// settings file must stop the build instead of degrading to a hidden default.
fn generate_viewer_settings(out_dir: &str) {
    let text = match std::fs::read_to_string(SETTINGS_FILE) {
        Ok(text) => text,
        Err(error) => panic!("read {SETTINGS_FILE}: {error}"),
    };
    let settings: Settings = match toml::from_str(&text) {
        Ok(settings) => settings,
        Err(error) => panic!("parse {SETTINGS_FILE}: {error}"),
    };
    let keystate = settings.viewer.keystate;
    check_range(
        "numlock_confirm_timeout_ms",
        keystate.numlock_confirm_timeout_ms,
        &NUMLOCK_CONFIRM_TIMEOUT_MS,
    );
    check_range(
        "dispatch_poll_interval_ms",
        keystate.dispatch_poll_interval_ms,
        &DISPATCH_POLL_INTERVAL_MS,
    );

    let generated = format!(
        "// Generated by build.rs from {SETTINGS_FILE} [viewer.keystate]. Do not edit.\n\
         const NUMLOCK_CONFIRM_TIMEOUT: std::time::Duration =\n    \
         std::time::Duration::from_millis({});\n\
         const DISPATCH_POLL_INTERVAL: std::time::Duration =\n    \
         std::time::Duration::from_millis({});\n",
        keystate.numlock_confirm_timeout_ms, keystate.dispatch_poll_interval_ms
    );
    let path = std::path::Path::new(out_dir).join("viewer_settings.rs");
    if let Err(error) = std::fs::write(&path, generated) {
        panic!("write {}: {error}", path.display());
    }
    println!("cargo:rerun-if-changed={SETTINGS_FILE}");
}

fn main() {
    let hash = std::process::Command::new("git")
        .args(["rev-parse", "--short", "HEAD"])
        .output()
        .ok()
        .and_then(|o| String::from_utf8(o.stdout).ok())
        .map(|s| s.trim().to_owned())
        .filter(|s| !s.is_empty())
        .unwrap_or_else(|| "unknown".to_owned());

    let build_file = ".build_number";
    let n: u32 = std::fs::read_to_string(build_file)
        .ok()
        .and_then(|s| s.trim().parse().ok())
        .unwrap_or(0)
        + 1;
    let _ = std::fs::write(build_file, n.to_string());

    println!("cargo:rustc-env=GIT_HASH={hash}");
    println!("cargo:rustc-env=BUILD_NUMBER={n}");

    // Cargo always sets OUT_DIR for a build script; a missing one means the
    // generated cursor and settings would land somewhere unpredictable.
    let out_dir = match std::env::var("OUT_DIR") {
        Ok(dir) => dir,
        Err(error) => panic!("OUT_DIR: {error}"),
    };

    generate_viewer_settings(&out_dir);

    // Rasterize the high-visibility cursor SVG once at build time so the binary
    // carries a ready-to-blit PNG (no runtime SVG engine). Height picked so the
    // overlay is clearly larger than any native 24/32px cursor.
    let svg_path = "cursor_v6_fixed.svg";
    let png_out = format!("{out_dir}/cursor.png");
    let status = std::process::Command::new("rsvg-convert")
        .args(["-h", "72", "-o", &png_out, svg_path])
        .status();
    match status {
        Ok(s) if s.success() => {}
        Ok(s) => panic!("rsvg-convert failed with status {s}"),
        Err(e) => panic!("rsvg-convert not runnable ({e}); install librsvg"),
    }
    println!("cargo:rerun-if-changed={svg_path}");

    // Run build.rs every build so GIT_HASH and BUILD_NUMBER are always fresh.
    println!("cargo:rerun-if-changed=NONEXISTENT_FILE_FORCE_RERUN");
}
